### ISSUE TITLE
[Question] Are all types manually written?

### ISSUE THREAD

**Issue by septatrix** [hexatester/moodlepy#10]
Hey I recently stumbled upon your project and was positively surprised how thoroughly everything was annotated.
I am currently in the process of writing basically the same and wanted to ask if these were all manually written or if you scanned the moodle code (or documentation page)?

**Comment by hexatester** [comment]
Currently, most of the type / anotation were manually copied from moodle webservice documentation with a lot of help from vscode.
I was trying to automate most of type generation but failed miserably, caused by inconsistency in moodle webservice documentation.

**Comment by septatrix** [comment]
Thanks for the quick response. I think I will still try to automate this using the PHP source directly. If I get it working I can let you know if you want to
