### ISSUE TITLE
[Feature Request ✨] User enrolment

### ISSUE THREAD

**Issue by meumesmo** [hexatester/moodlepy#2]
Dear Hexatester, 

I'm very glad you're developing this library! I have a moodle website and I tested your lib and it worked well. I'm not a very experienced developer and I'd love to have the function of enrolling students thought the web service. 
Could you provide me some help?

Thanks a lot!

**Comment by hexatester** [comment]
I'm glad to hear that.

For enrolling students from web service you might need to call `enrol_manual_enrol_users` moodle ws function.
Provided that the users and the courses are already in the system.
For more information check your moodle site ws documentation.

Thanks.

**Comment by hexatester** [comment]
And if you want me to add it into _moodlepy_. Just sent me the function's docs, from your moodle site's web service documentation.

_Example_ : https://pastebin.com/GqGP3s82

**Comment by hexatester** [comment]
This is an example for manually enroling a user using webservice.
```python
from datetime import datetime
from moodle.enrol.manual import Enrolment

m = Moodle.login('https://sandbox.moodledemo.net', 'admin', 'sandbox')
enrolment = Enrolment(
    roleid=1,  # Role to assign to the user
    userid=1,  # The user that is going to be enrolled
    courseid=1,  # The course to enrol the user role in
    timestart=datetime.now(),  # Timestamp when the enrolment start
    timeend=datetime(2021, 6, 1),  # Timestamp when the enrolment end
    suspend=0,  # set to 1 to suspend the enrolment
)
enrolments = [enrolment]
m.enrol.manual.enrol_users(enrolments)  # enrol_manual_enrol_users
```

**Comment by hexatester** [comment]
I closed this issue because the feature has been implemented, if you have more questions please create a new issue. Thank you!
