### ISSUE TITLE
mod_page_view_page

### ISSUE THREAD

**Issue by JPatagonico** [hexatester/moodlepy#7]
Please,
Can you incorporate mod_page_view_page?
I have tried:
arguments3 = {
   "pageid": 11
}
contents = moodle ('mod_page_view_page', ** arguments3)

And it returned: "moodle.exception.MoodleException"

Thank you

**Comment by hexatester** [comment]
Try
```python
contents = moodle.mod.page.view_page(pageid=11)
```

**Comment by JPatagonico** [comment]
its works. Thanks.

**Comment by hexatester** [comment]
You're welcome
