### ISSUE TITLE
[Doc Request ✨]

### ISSUE THREAD

**Issue by gaetan1903** [hexatester/moodlepy#8]
Hi, very good moodle python 🥇 

I don't know how send parametre on a function with your module, 

Can you show me ?

**Comment by gaetan1903** [comment]
I look your code and now, I know it, 

The issue can be closed now

**Comment by hexatester** [comment]
You can read full moodle webservice documentation in [sandbox moodledemo](https://sandbox.moodledemo.net/admin/webservice/documentation.php), login as `admin` with password `sandbox`.
